# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
# contains an end to end validation pipeline using C# compilation tests for staging beta metadata

# capture-metadata.yml will result in the capture and cleaning of the metadata 
# with the artifacts posted to GitHub.

parameters:
- name: 'endpoint'
  type: string 
  default: "v1.0"
- name: 'inputMetadata'
  type: string 
  default: $(rawMetadataFileV1)
- name: 'outputPath'
  type: string
  default: $(System.ArtifactsDirectory)
- name: 'docsDirectory'
  type: string
  default: $(docsDirectoryV1)
  
steps:

# We only need the scripts
- checkout: self
  displayName: checkout generator
  fetchDepth: 1
  persistCredentials: true

- checkout: microsoft-graph-docs
  displayName: checkout graph docs
  fetchDepth: 1
  persistCredentials: true

- template: checkout-metadata.yml
- template: set-user-config.yml

# Results in a raw metadata file written to microsoftgraph/msgraph-metadata if there are changes.
# An error will cancel this step if there are no changes.
- pwsh: '$(scriptsDirectory)/download-diff-metadata.ps1'
  # workingDirectory: 'msgraph-metadata'
  displayName: 'Diff and publish ${{ parameters.endpoint }} metadata'
  env:
    errorOnNoChange: 1
    endpointVersion: ${{ parameters.endpoint }}
    targetBranch: 'master'
  enabled: false

- template: download-typewriter.yml

## Only run if the previous step was successful
- pwsh: '$(scriptsDirectory)/run-typewriter-clean-metadata.ps1'
  env:
    OutputPath: ${{ parameters.outputPath }}
    InputMetadataFile: ${{ parameters.inputMetadata }}
    TypewriterExecutable: $(typewriterExecutable)
    TypewriterDirectory: $(typewriterDirectory)
    DocsDirectory: ${{ parameters.docsDirectory }}
    GenerationMode: 'TransformWithDocs'
    Transform: $(transformScript)
  displayName: 'Run Typewriter to clean ${{ parameters.endpoint }} metadata'

# Use the clean metadata from the last step to generate DotNet files.

- template: use-dotnet-sdk.yml

- pwsh: '$(scriptsDirectory)/run-typewriter.ps1'
  env:
    BuildConfiguration: $(buildConfiguration)
    OutputPath: output
    CleanMetadataFile: $(cleanMetadataFileV1)
    TypewriterExecutable: $(typewriterExecutable)
    TypewriterDirectory: $(typewriterDirectory)
    Language: 'CSharp'
    Endpoint:  ${{ parameters.endpoint }}
  displayName: 'Generate ${{ parameters.endpoint }} files for .NET'

- checkout: msgraph-sdk-dotnet
  displayName: checkout dotnet v1
  fetchDepth: 1
  persistCredentials: true

- pwsh: '$(scriptsDirectory)/copy-dotnet-models.ps1'
  displayName: 'Update models .NET models'
  env:
    BuildConfiguration: $(buildConfiguration)
    OutputFullPath: $(typewriterDirectory)/output
    RepoModelsDir: $(Build.SourcesDirectory)/msgraph-sdk-dotnet/src/Microsoft.Graph/Generated/

# Smoke test that the generated files build for .NET
- task: DotNetCoreCLI@2
  displayName: Build Microsoft.Graph.dll
  inputs:
    command: 'build'
    projects: msgraph-sdk-dotnet/**/*.csproj
    arguments: '--configuration $(buildConfiguration)'

# Checkin clean metadata into metadata repo or make it an artifact.
- pwsh: |
    Write-Host "About to add clean metadata file....."
    Push-Location -Path "$(Build.SourcesDirectory)/msgraph-metadata"

    git add . | Write-Host
    if ($env:BUILD_REASON -eq 'Manual') # Skip CI if manually running this pipeline.
    {
        git commit -m "Update clean metadata file with $env:BUILD_BUILDID [skip ci]" | Write-Host
    }
    else
    {
        git commit -m "Update clean metadata file with $env:BUILD_BUILDID" | Write-Host
    }

    Write-Host "Added and commited cleaned metadata." -ForegroundColor Green

    # git push --set-upstream origin master | Write-Host
    Write-Host "Pushed the results of the build to the master branch." -ForegroundColor Green
    Pop-Location
  displayName: Push clean ${{ parameters.endpoint }} to msgraph-metadata repo
  enabled: true